### PR TITLE
Update How-secure-is-portugal.md

### PR DESCRIPTION
**Pull request by Ambg05**
I'm leaving the notes at the bottom of this file in situ for now.

### CODE REVIEW

**Comment by DinisCruz** [comment]
Btw don't delete these mappings

```
----
 -layout: default
 -title: How Secure is Portugal
 -type: research
 ----
```

since they are what makes the pages at https://github.com/DinisCruz/keynote-bsideslisbon apear

**Comment by DinisCruz** [comment]
can you add them back?

**Comment by Ambg05** [comment]
Oops! Yes, I'll add them back.

**Comment by Ambg05** [comment]
Do I just add them back to the files that had them originally, or do I add them to each file I create as well?

**Comment by DinisCruz** [comment]
both

**Pull request merged**
