### PR TITLE
Update Past-innovations.md

### PR DESCRIPTION
**Pull request by Ambg05**

### CODE REVIEW

**Comment by DinisCruz** [comment]
small note

the metatada at the top does no use the - (dash) on the field names, and it uses 3 - on the top (---)

it is 

```
---
layout: default
title: Past innovations
type: research
---
```

vs
```
----
 -layout: default
 -title: Past innovations
 -type: research
 ----
```

You can see it is ok if it looks like this

image

vs like this

image

**Comment by DinisCruz** [comment]
and it shows up at https://diniscruz.github.io/keynote-bsideslisbon/

image

**Comment by DinisCruz** [comment]
btw you should be able to configure your fork to show the site at https://ambg05.github.io/keynote-bsideslisbon/

**Comment by Ambg05** [comment]
Thanks!

**Pull request merged**
